/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TranslatorPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  apiKey: "",
  outputMode: "replace",
  systemPrompt: `\u4F60\u662F\u4E13\u4E1A\u7684SEO\u5185\u5BB9\u7FFB\u8BD1\u4E13\u5BB6\u3002\u5C06\u4EE5\u4E0B\u82F1\u6587\u7FFB\u8BD1\u4E3A\u7B80\u4F53\u4E2D\u6587\uFF0C\u8981\u6C42\uFF1A
1. \u4FDD\u6301 SEO \u5173\u952E\u8BCD\u7684\u51C6\u786E\u6027
2. \u8BED\u8A00\u81EA\u7136\u6D41\u7545\uFF0C\u7B26\u5408\u4E2D\u6587\u6BCD\u8BED\u4E60\u60EF
3. \u4FDD\u7559 Markdown \u683C\u5F0F\uFF08\u6807\u9898\u3001\u52A0\u7C97\u3001\u5217\u8868\u7B49\uFF09
4. \u53EA\u8F93\u51FA\u7FFB\u8BD1\u7ED3\u679C\uFF0C\u4E0D\u52A0\u4EFB\u4F55\u89E3\u91CA`,
  temperature: 0.3
};
var TranslatorSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "DeepSeek \u7FFB\u8BD1\u63D2\u4EF6\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("DeepSeek API Key").setDesc("\u4ECE platform.deepseek.com \u83B7\u53D6\u4F60\u7684 API Key").addText(
      (text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value.trim();
        await this.plugin.saveSettings();
      })
    ).then((setting) => {
      var _a;
      (_a = setting.controlEl.querySelector("input")) == null ? void 0 : _a.setAttribute("type", "password");
    });
    new import_obsidian.Setting(containerEl).setName("\u8F93\u51FA\u6A21\u5F0F").setDesc("\u7FFB\u8BD1\u7ED3\u679C\u7684\u8F93\u51FA\u65B9\u5F0F").addDropdown(
      (drop) => drop.addOption("replace", "\u66FF\u6362\u539F\u6587").addOption("append", "\u8FFD\u52A0\u5728\u4E0B\u65B9").addOption("new-note", "\u65B0\u5EFA\u7B14\u8BB0").setValue(this.plugin.settings.outputMode).onChange(async (value) => {
        this.plugin.settings.outputMode = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Temperature").setDesc(`\u63A7\u5236\u8F93\u51FA\u7684\u968F\u673A\u6027\uFF08\u5F53\u524D\uFF1A${this.plugin.settings.temperature}\uFF09\u3002\u7FFB\u8BD1\u5EFA\u8BAE\u4F7F\u7528\u8F83\u4F4E\u503C\uFF080.3\uFF09\u3002`).addSlider(
      (slider) => slider.setLimits(0, 1, 0.1).setValue(this.plugin.settings.temperature).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.temperature = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u7CFB\u7EDF Prompt").setDesc("\u53D1\u9001\u7ED9 DeepSeek \u7684\u7CFB\u7EDF\u6307\u4EE4\uFF0C\u5B9A\u4E49\u7FFB\u8BD1\u98CE\u683C\u548C\u89C4\u5219").addTextArea((text) => {
      text.setPlaceholder("\u8F93\u5165\u7CFB\u7EDF prompt...").setValue(this.plugin.settings.systemPrompt).onChange(async (value) => {
        this.plugin.settings.systemPrompt = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.rows = 8;
      text.inputEl.style.width = "100%";
      text.inputEl.style.fontFamily = "monospace";
      text.inputEl.style.fontSize = "12px";
    });
  }
};

// api.ts
var import_obsidian2 = require("obsidian");
var DEEPSEEK_API_URL = "https://api.deepseek.com/v1/chat/completions";
async function translateText(text, settings) {
  var _a, _b, _c;
  if (!settings.apiKey) {
    throw new Error("\u672A\u914D\u7F6E API Key\uFF0C\u8BF7\u5728\u63D2\u4EF6\u8BBE\u7F6E\u4E2D\u586B\u5199");
  }
  let response;
  try {
    response = await (0, import_obsidian2.requestUrl)({
      url: DEEPSEEK_API_URL,
      method: "POST",
      headers: {
        "Authorization": `Bearer ${settings.apiKey}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: "deepseek-chat",
        temperature: settings.temperature,
        messages: [
          { role: "system", content: settings.systemPrompt },
          { role: "user", content: text }
        ]
      }),
      throw: false
    });
  } catch (err) {
    throw new Error("\u7F51\u7EDC\u8FDE\u63A5\u8D85\u65F6\uFF0C\u8BF7\u91CD\u8BD5");
  }
  if (response.status === 401) {
    throw new Error("API Key \u65E0\u6548\uFF0C\u8BF7\u5728\u8BBE\u7F6E\u4E2D\u68C0\u67E5");
  }
  if (response.status === 402) {
    throw new Error("API \u8D26\u6237\u4F59\u989D\u4E0D\u8DB3\uFF0C\u8BF7\u5145\u503C\u540E\u91CD\u8BD5");
  }
  if (response.status === 429) {
    throw new Error("\u8BF7\u6C42\u8FC7\u4E8E\u9891\u7E41\uFF0C\u8BF7\u7A0D\u540E\u91CD\u8BD5");
  }
  if (response.status !== 200) {
    throw new Error(`API \u8BF7\u6C42\u5931\u8D25\uFF08\u72B6\u6001\u7801 ${response.status}\uFF09`);
  }
  const json = response.json;
  const content = (_c = (_b = (_a = json == null ? void 0 : json.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content;
  if (!content) {
    throw new Error("API \u8FD4\u56DE\u4E86\u7A7A\u7684\u7FFB\u8BD1\u7ED3\u679C");
  }
  return content.trim();
}

// main.ts
var TranslatorPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new TranslatorSettingTab(this.app, this));
    this.addCommand({
      id: "translate-to-chinese",
      name: "\u7FFB\u8BD1\u4E3A\u4E2D\u6587",
      editorCallback: (editor, ctx) => {
        const view = ctx instanceof import_obsidian3.MarkdownView ? ctx : this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
        if (view)
          this.translateSelection(editor, view);
      }
    });
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor) => {
        if (editor.getSelection().trim()) {
          menu.addItem(
            (item) => item.setTitle("\u7FFB\u8BD1\u4E3A\u4E2D\u6587").setIcon("languages").onClick(() => {
              const view = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
              if (view) {
                this.translateSelection(editor, view);
              }
            })
          );
        }
      })
    );
  }
  async translateSelection(editor, view) {
    var _a, _b;
    const selectedText = editor.getSelection() || editor.getValue();
    if (!selectedText.trim()) {
      new import_obsidian3.Notice("\u8BF7\u5148\u9009\u4E2D\u9700\u8981\u7FFB\u8BD1\u7684\u6587\u672C");
      return;
    }
    const loadingNotice = new import_obsidian3.Notice("\u7FFB\u8BD1\u4E2D...", 0);
    try {
      const result = await translateText(selectedText, this.settings);
      loadingNotice.hide();
      switch (this.settings.outputMode) {
        case "replace":
          editor.replaceSelection(result);
          break;
        case "append": {
          const cursor = editor.getCursor("to");
          editor.replaceRange("\n\n" + result, cursor);
          break;
        }
        case "new-note": {
          const baseName = (_b = (_a = view.file) == null ? void 0 : _a.basename) != null ? _b : "Translation";
          const fileName = `[\u8BD1] ${baseName}`;
          const vault = this.app.vault;
          const existing = vault.getAbstractFileByPath(`${fileName}.md`);
          const finalName = existing ? `${fileName} ${Date.now()}` : fileName;
          const newFile = await vault.create(`${finalName}.md`, result);
          await this.app.workspace.openLinkText(newFile.path, "", true);
          break;
        }
      }
      new import_obsidian3.Notice("\u7FFB\u8BD1\u5B8C\u6210 \u2713");
    } catch (err) {
      loadingNotice.hide();
      const msg = err instanceof Error ? err.message : String(err);
      new import_obsidian3.Notice(`\u7FFB\u8BD1\u5931\u8D25\uFF1A${msg}`, 5e3);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
